apiVersion: apps/v1
kind: Deployment
metadata:
  name: line-ten-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: line-ten
  template:
    metadata:
      labels:
        app: line-ten
    spec:
      containers:
        - name: line-ten
          image: wassimbzn/line-ten:v1.0
          ports:
            - containerPort: 3000            # Ensure this is the correct port for your app
          readinessProbe:
            httpGet:
              path: /health                  # Ensure this matches your app’s health route
              port: 3000                     # Update this port if your app uses something other than 80
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: line-ten-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: line-ten

