version: '3.8'

services:
  line-ten-app:
    # Build the image from the Dockerfile in the current directory
    build:
      context: .
      dockerfile: Dockerfile
    # Container will restart automatically on failures
    restart: unless-stopped
    ports:
      - "3000:3000"  # Host port : Container port

    environment:
      - NODE_ENV=production

    command: ["npm", "start"]