#this deployment file is for minikube
apiVersion: apps/v1
kind: Deployment
metadata:
  name: line-ten
spec:
  replicas: 1
  selector:
    matchLabels:
      app: line-ten
  template:
    metadata:
      labels:
        app: line-ten
    spec:
      containers:
        - name: line-ten
          image: line-ten       # This should match the Docker image name in local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000  #  this matches the port of the dockerfile