apiVersion: apps/v1
kind: Deployment
metadata:
  name: line-ten-deployment
spec:
  # here i'm specifying 2 replicas or the number of the pods that i want to load balance on
  replicas: 2
  selector:
    matchLabels:
      app: line-ten
  template:
    metadata:
      labels:
        app: line-ten
    spec:
      containers:
        - name: line-ten
          image: wassimbzn/line-ten:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000            # this the port that i will use and it will be the same as the docker file's port
          readinessProbe:
            httpGet:
              path: /
              port: 3000                     # after deploying the pod this healthcheck will curl check if it's accessible or not for the app
            initialDelaySeconds: 10
            periodSeconds: 5
