name: CI/CD Pipeline for Line-Ten App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install --no-audit


      #- name: Run Tests
      #  run: npm test

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/line-ten:${{ github.sha }} .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker Image to Docker Hub
        run: docker push "${{ secrets.DOCKER_HUB_USERNAME }}"/line-ten:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set Azure Config Directory
        run: mkdir -p /tmp/.azure

      - name: Log in to Azure CLI
        uses: azure/cli@v1
        env:
          AZURE_CONFIG_DIR: /tmp/.azure
        with:
          inlineScript: |
            az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group line-ten-rg --name line-ten-aks --overwrite-existing

      - name: Deploy to AKS
        env:
            AZURE_CONFIG_DIR: /tmp/.azure
        run: |
          kubectl apply -f k8s/deployment.yaml
